# Generated by Django 3.2 on 2021-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='/media/logo_gray.png', upload_to='images/'),
        ),
    ]
