# Generated by Django 3.2 on 2021-05-04 12:43

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210504_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=web.models.LimitedImageField(blank=True, upload_to=''),
        ),
    ]
