# Generated by Django 3.2 on 2021-05-08 13:16

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='additional_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='Федеральная сеть центров образования цифрового, естественнонаучного, технического и гуманитарного профилей, организованная в рамках проекта "Современная школа".', help_text='Description must not exceed 160 characters.', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=web.models.LimitedImageField(default='images/1000x1000.jpg', help_text='Header image should be 1000x1000 in size.', upload_to='images/', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title must not exceed 35 characters.', max_length=35),
        ),
    ]
