# Generated by Django 3.2 on 2021-05-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210508_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostAdditional',
        ),
    ]
