# Generated by Django 3.2 on 2021-05-08 13:39

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210508_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', web.models.LimitedImageField(upload_to='images/', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostAdditionalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
