# Generated by Django 3.2 on 2021-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210508_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadditionalimages',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PostAdditionalText',
        ),
    ]
