# Generated by Django 3.2 on 2021-05-08 15:33

from django.db import migrations
import tinymce.models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210508_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='postadditionalimages',
            name='image',
            field=web.models.LimitedImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
